### ISSUE TITLE
predict the confidence map

### ISSUE THREAD

**Issue by ZhouCX117** [Carlisle-Liu/OCENet#1]
Hi, thanks for your excellent work. However, there seems a small problem when predicting the confidence map. The channels of the feature map are 4 after concatting. 
![image](https://user-images.githubusercontent.com/79554332/148551287-e0e23ca4-095a-474a-a4fe-5ebb29524d1e.png)

**Comment by Carlisle-Liu** [comment]
Change "1" to "4" at line 23 of "ResNet_models.py" will fix the issue. I have updated the corresponding files.

**Comment by ZhouCX117** [comment]
Could you please provide the trained models and test images?

**Comment by Carlisle-Liu** [comment]
Will update those soon.

**Comment by ZhouCX117** [comment]
Thank you!!

**Comment by ZhouCX117** [comment]
Hi, it is me again! There seem several small mistakes in your test file.
And could the image size differ when training distributionally on different GPU cards?

**Comment by Carlisle-Liu** [comment]
Hi,

No, the image size must be the same when training distributionally.

Will clean up the files soon.   Just fixed my PC.  Had screwed my cuda trying to install apex package few days earlier.

**Comment by Carlisle-Liu** [comment]
Hi,

Saliency maps and code files have been updated.
