### ISSUE TITLE
关于置信度估计网络的问题

### ISSUE THREAD

**Issue by IceHowe** [Carlisle-Liu/OCENet#3]
请问为什么要用网络去预测这个预测值与真值的误差，既然这误差可以反映难易程度，为什么不直接用这个进行加权处理，而是用网络去预测这个值，再用这个预测的值去加权？

**Comment by Carlisle-Liu** [comment]
The OCENet is intended primarily to approximate the inaccuracy as model uncertainty. It is certainty viable to use directly the difference between the prediction and the ground-truth to weight the loss function.
