### ISSUE TITLE
the results do not match the results provided by your paper

### ISSUE THREAD

**Issue by dante1024** [Carlisle-Liu/OCENet#4]
I would like to ask, I downloaded your prediction maps, and then tested the indicators, and found that the results do not match the results provided by your paper, what is going on?

![VTHMP@I6~X31T_EE$1ENHBL](https://user-images.githubusercontent.com/60936436/231097905-9b4e5f6a-b6bc-4998-b7b2-4c3d9cb8c0dd.png)

**Comment by Carlisle-Liu** [comment]
The latest results are obtained after the paper was accepted. They are regarded as overall better than the results included in the paper.
